/**
 * Knowledge promote sub-flow — orchestrator (the "flow within a flow").
 *
 * Runs ingest -> distill -> link -> health over a completed session directory
 * and lands every output as a DRAFT for the promote step's human/agent to apply.
 * PROPOSALS-ONLY (R4): the default target writes under `<session>/proposals/`;
 * the explicit store target stages under the personal store's pending area.
 * Neither target writes docs, CONTEXT.md, or live Knowledge records.
 *
 * FlowDefinition: kits/knowledge/flows/promote.flow.json (id `knowledge.promote`).
 * See context/contracts/knowledge-store-contract.md and
 * context/contracts/decision-registry-contract.md.
 *
 * @module promote
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { ingestSession } from "./ingest.js";
import { distill } from "./distill.js";
import { link } from "./link.js";
import { health } from "./health.js";
import { sanitizeStoreResult, writeStoreProposals } from "./store-target.js";

export {
  ingestFromSource,
  ingestRuntimeSessions,
  ingestSession,
  SESSION_SOURCE_IDS,
} from "./ingest.js";
export { scrubRuntimeResidueText } from "./runtime-session.js";
export { distill } from "./distill.js";
export { link } from "./link.js";
export { health } from "./health.js";
export { snapshotDir, validateDecisionDelta } from "./lib.js";

function renderVocabulary(vocabulary) {
  const lines = [
    "# Proposed CONTEXT.md vocabulary additions",
    "",
    "Add each subject noun to the `## Glossary` section of CONTEXT.md before its",
    "decision topic is filed (the registry slug rule keys off CONTEXT.md vocabulary).",
    "",
  ];
  for (const v of vocabulary) {
    lines.push(`### ${v.term}`, "", v.definition || "(define this term)", "");
  }
  if (vocabulary.length === 0) lines.push("_No new vocabulary — every decision subject already exists in CONTEXT.md._", "");
  return lines.join("\n");
}

function renderLearning(rec) {
  const lines = [
    "---",
    `id: ${rec.id}`,
    rec.outcome ? `outcome: ${rec.outcome}` : "outcome: neutral",
    "---",
    "",
    `# ${rec.title}`,
    "",
    rec.body || "",
    "",
  ];
  if (rec.source_refs && rec.source_refs.length) {
    lines.push("## Source refs", "");
    for (const r of rec.source_refs) lines.push(`- ${r}`);
    lines.push("");
  }
  if (rec.correction) {
    lines.push("## Correction", "", `- type: ${rec.correction.type || "n/a"}`, `- recurrence_key: ${rec.correction.recurrence_key || "n/a"}`, "");
  }
  return lines.join("\n");
}

function renderReadme(result) {
  return [
    `# Promote proposals — session ${result.slug}`,
    "",
    "Generated by the Knowledge Kit promote sub-flow (`knowledge.promote`).",
    "Everything here is a DRAFT PROPOSAL. Nothing was written to docs/ or CONTEXT.md.",
    "The promote step's human/agent applies these, then records them with the `promote` CLI.",
    "",
    "## Apply order",
    "",
    "1. `vocabulary.md` — add any new subject nouns to CONTEXT.md `## Glossary`.",
    "2. `decisions/*.md` — file each as `docs/decisions/<slug>.md`, then `npm run gen:decisions-index` + `npm run check:decisions`.",
    "3. `learnings/*.md` — record via the learning sink / `docs/learnings/`.",
    "4. `health/` — if a contradiction report + merge-repair proposal is present, apply the merge target edit.",
    "",
    "## Contents",
    "",
    `- decisions: ${result.decisions.map((d) => d.slug).join(", ") || "(none)"}`,
    `- vocabulary additions: ${result.vocabulary.map((v) => v.term).join(", ") || "(none)"}`,
    `- learnings: ${result.learnings.length}`,
    `- touched topics: ${result.manifest.touched_topics.join(", ") || "(none)"}`,
    `- contradiction findings: ${result.health.report.summary.finding_count}`,
    `- merge-repair proposals: ${result.health.mergeProposals.length}`,
    "",
  ].join("\n");
}

/** Write every draft ONLY under outDir. Returns the list of relative paths written. */
function writeProposals(outDir, linked, healthResult, result) {
  const written = [];
  const write = (rel, content) => {
    const abs = path.join(outDir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content, "utf8");
    written.push(rel);
  };

  for (const d of linked.decisions) write(path.join("decisions", `${d.slug}.md`), d.rendered);
  write("vocabulary.md", renderVocabulary(linked.vocabulary));
  for (const rec of linked.learnings) write(path.join("learnings", `${rec.id}.md`), renderLearning(rec));
  write("link-manifest.json", `${JSON.stringify(linked.manifest, null, 2)}\n`);
  write(path.join("health", "contradiction-report.json"), `${JSON.stringify(healthResult.report, null, 2)}\n`);
  if (healthResult.mergeProposals.length) {
    write(path.join("health", "merge-proposals.json"), `${JSON.stringify(healthResult.mergeProposals, null, 2)}\n`);
    for (const mp of healthResult.mergeProposals) {
      write(path.join("health", `merge-repair-${mp.target.tombstone}.md`), mp.rendered);
    }
  }
  write("promote-result.json", `${JSON.stringify(result, null, 2)}\n`);
  write("README.md", renderReadme(result));
  return written;
}

/**
 * Run the promote sub-flow over a completed session directory.
 *
 * @param {object} opts
 * @param {string} opts.sessionDir            absolute path to the completed session dir.
 * @param {string} opts.repoRoot              repo root (registry + CONTEXT.md live here).
 * @param {object} [opts.provenance]          { pr, mergeSha, sessionArchivePath }.
 * @param {string} [opts.outDir]              proposals dir (default <sessionDir>/proposals).
 * @param {"repo-docs"|"store"} [opts.target="repo-docs"] proposal destination.
 * @param {object} [opts.env=process.env]      environment used to resolve a store target.
 * @param {string} [opts.decided]             ISO date stamped on drafts.
 * @param {string} [opts.agent]
 * @param {boolean} [opts.write=true]         stage drafts; false validates and reports paths only.
 * @returns {Promise<object>} the promote result.
 */
function targetOptions(opts, sessionDir) {
  const target = opts.target || "repo-docs";
  if (!new Set(["repo-docs", "store"]).has(target)) {
    throw new Error(`runPromote: unknown target '${target}'; expected repo-docs or store`);
  }
  if (target === "store" && opts.outDir) {
    throw new Error("runPromote: { outDir } is only valid for the repo-docs target");
  }
  return { target, repoDocsOutDir: opts.outDir || path.join(sessionDir, "proposals") };
}

function promoteResult(residue, linked, healthResult, repoDocsOutDir, distilled) {
  return {
    schema_version: "1.0",
    flow: "knowledge.promote",
    slug: residue.slug,
    repo: residue.repo,
    out_dir: repoDocsOutDir,
    ingested: {
      session_markdown: residue.sessionMarkdown,
      status: residue.status,
      decision_candidates: residue.decisions.length,
      learning_records: residue.learnings.length,
      transcript_refs: residue.transcriptRefs,
      touched_files: residue.touchedFiles,
    },
    decisions: linked.decisions.map((d) => ({ slug: d.slug, subject: d.subject, evidence: d.evidence, new_vocabulary: d.newVocabulary })),
    vocabulary: linked.vocabulary,
    learnings: linked.learnings,
    manifest: linked.manifest,
    health: {
      report: healthResult.report,
      mergeProposals: healthResult.mergeProposals,
    },
    warnings: distilled.warnings,
  };
}

function finishPromote({ target, write, linked, residue, result, env, agent, repoDocsOutDir, healthResult }) {
  if (target === "store") {
    const staged = writeStoreProposals({ linked, residue, env, agent: agent || "knowledge.promote", write });
    result.out_dir = staged.outDir;
    result.written = staged.written;
    return sanitizeStoreResult(result);
  }
  result.written = write ? writeProposals(repoDocsOutDir, linked, healthResult, result) : [];
  return result;
}

export async function runPromote(opts = {}) {
  const { sessionDir, repoRoot, provenance = {}, decided, agent, write = true } = opts;
  if (!sessionDir) throw new Error("runPromote requires { sessionDir }");
  if (!repoRoot) throw new Error("runPromote requires { repoRoot }");
  const { target, repoDocsOutDir } = targetOptions(opts, sessionDir);
  const residue = ingestSession(sessionDir, { agent });
  const distilled = distill(residue, { repoRoot, decided });
  const linked = await link(distilled, provenance, { repoRoot, agent });
  const healthResult = await health({ repoRoot, draftDecisions: linked.decisions, agent });
  const result = promoteResult(residue, linked, healthResult, repoDocsOutDir, distilled);
  return finishPromote({
    target, write, linked, residue, result, env: opts.env || process.env,
    agent, repoDocsOutDir, healthResult,
  });
}

export default runPromote;
