import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createClaudeCodeAdapter, createStrandsAdapter } from "@kontourai/conduit";
import { generateHostConformanceEvidence } from "../conduit-host-integration.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const reportPath = path.join(root, "evals/reference/conduit-host-conformance/report.json");
const matrixPath = path.join(root, "docs/specs/host-integration-conformance.md");

function bindings() {
  const local = createClaudeCodeAdapter({
    resolveTarget: (asset) => `flow-agents-host/${asset.kind}/${asset.id}`,
    write: () => undefined,
  });
  const embedded = createStrandsAdapter({
    installAsset: () => undefined,
    applyOutcome: (_event, outcome) => outcome,
  });
  return [
    {
      adapter: local,
      evidenceScope: "adapter-contract" as const,
      adapterVersion: "0.2.1",
      hostId: "flow-agents-local-harness-binding",
      hostVersion: "public-config-binding-v1",
    },
    {
      adapter: embedded,
      evidenceScope: "adapter-contract" as const,
      adapterVersion: "0.2.1",
      hostId: "flow-agents-in-process-binding",
      hostVersion: "caller-bound-hooks-v1",
    },
  ];
}

function checkFile(file: string, expected: string): boolean {
  return fs.existsSync(file) && fs.readFileSync(file, "utf8") === expected;
}

export async function main(args = process.argv.slice(2)): Promise<number> {
  const generated = await generateHostConformanceEvidence(bindings());
  const matrix = [
    "# Host integration conformance",
    "",
    "> Generated by `npm run host-conformance` through `@kontourai/conduit` 0.2.1.",
    "> These rows prove Flow Agents bindings against the adapter contract; they are not live-host certification.",
    "",
    generated.matrix.trimEnd(),
    "",
  ].join("\n");
  if (args.includes("--check")) {
    if (!checkFile(reportPath, generated.json) || !checkFile(matrixPath, matrix)) {
      console.error("host conformance evidence is stale; run npm run host-conformance");
      return 1;
    }
    console.log("Host conformance evidence is current.");
    return 0;
  }
  fs.mkdirSync(path.dirname(reportPath), { recursive: true });
  fs.mkdirSync(path.dirname(matrixPath), { recursive: true });
  fs.writeFileSync(reportPath, generated.json);
  fs.writeFileSync(matrixPath, matrix);
  console.log(`Wrote ${path.relative(root, reportPath)} and ${path.relative(root, matrixPath)}.`);
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = await main();
}
